name: PR Test

on:
  pull_request_target:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_SHA: ${{ github.event.pull_request.base.sha }}
      HEAD_SHA: ${{ github.event.pull_request.head.sha }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: '${{ env.HEAD_SHA }}'

      - name: Get changed files and operations
        run: |
          # 使用 GitHub API 获取变更文件列表及其操作
          DIFF_FILES=$(gh api repos/${{ github.repository }}/compare/${{ env.BASE_SHA }}...${{ env.HEAD_SHA }} \
            --jq '.files | .[] | {filename, status}')
          echo "Changed files and operations: ${DIFF_FILES}"

          # 过滤出相关文件及其操作
          GIT_DIFF_CONTENT=$(echo "${DIFF_FILES}" | jq -r '.filename')
          GIT_DIFF_OPERATIONS=$(echo "${DIFF_FILES}" | jq -r '.status')
          echo "Filtered files: ${GIT_DIFF_CONTENT}"
          echo "File operations: ${GIT_DIFF_OPERATIONS}"

          # 将结果存储在环境变量中
          echo "GIT_DIFF_CONTENT=${GIT_DIFF_CONTENT}" >> $GITHUB_ENV
          echo "GIT_DIFF_OPERATIONS=${GIT_DIFF_OPERATIONS}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
        if: ${{ env.GIT_DIFF_CONTENT }}
        with:
          repository: ${{ github.repository }}
          ref: '${{ env.BASE_SHA }}'
          path: base-repo

      - name: Replace changed files
        if: ${{ env.GIT_DIFF_CONTENT }}
        run: |
          IFS=$'\n'
          for file in ${{ env.GIT_DIFF_CONTENT }}; do
            operation=$(echo "${GIT_DIFF_OPERATIONS}" | grep -m 1 -F "$file")
            if [ "$operation" = "modified" ] || [ "$operation" = "added" ]; then
              cp "base-repo/$file" "$file"
            elif [ "$operation" = "removed" ]; then
              rm -f "$file"
            fi
          done

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Eslint
        if: ${{ env.GIT_DIFF_CONTENT }}
        run: |
          yarn eslint ${{ env.GIT_DIFF_CONTENT }}

      - name: Run Build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

      - name: Archive build dist
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: dist

      - name: Archive examples
        uses: actions/upload-artifact@v4
        with:
          name: build-examples
          path: examples

  review:
    needs: build
    permissions: write-all
    uses: ./.github/workflows/pr-reviewer.yml
    secrets: inherit
